### PR TITLE
43 add more repetition checks for tests

### LINKED ISSUE #43: Add more repetition checks for tests

### PR DESCRIPTION
**Pull request by gliargovas**

### CODE REVIEW

**Comment by angelhof** [comment]
Looks good to me, thanks! we can merge as long as the timing in tests is robust (if the tests pass with very high probability on atlas+cloudlab due to timing).

**Comment by angelhof** [comment]
@gliargovas Are we close to merging this? What is its status?

**Comment by gliargovas** [comment]
@angelhof tests pass both locally and on cloudlab. Commented-out anything inconsistent. Feel free to merge :-)

**Comment by angelhof** [comment]
Great, looks good. @gliargovas  Could you first merge with main (`git fetch --all; git merge origin/main`) and rerun the tests on your machine? I have merged some PRs in main and I just want to make sure that when merging nothing has broken. If tests pass, feel free to merge :)

**Comment by gliargovas** [comment]
@angelhof Made a minor change to the log level of the repetitions check (previously `TRACE`, now `DEBUG`). Tests pass and are consistent. Feel free to merge :-)

**Comment by angelhof** [comment]
Great, merged, thank you :)

**Pull request merged**
